-----------------------------------------------------------------------------------------
--                                    TRIGGERS
-----------------------------------------------------------------------------------------

-- Trigger que executa a função NORMALIZAR_EMAIL() na tabela CLIENTE
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_EMAIL_CLIENTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_EMAIL();


-- Trigger que executa a função NORMALIZAR_EMAIL() na tabela FUNCIONARIO
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_EMAIL_FUNCIONARIO
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_EMAIL();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela CLIENTE
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_CLIENTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela FUNCIONARIO
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_FUNCIONARIO
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela NOME_ITEM
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_ITEM
BEFORE INSERT OR UPDATE ON ITEM
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela NOME_MODELO
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_MODELO
BEFORE INSERT OR UPDATE ON MODELO
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela NOME_MONTADORA
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_MONTADORA
BEFORE INSERT OR UPDATE ON MONTADORA
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_NOME() na tabela TIPO_ITEM
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_NOME_TIPO_ITEM
BEFORE INSERT OR UPDATE ON TIPO_ITEM
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_NOME();


-- Trigger que executa a função NORMALIZAR_PLACA na tabela VEICULO
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_PLACA
BEFORE INSERT OR UPDATE ON VEICULO
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_PLACA();


-- Trigger que executa a função NORMALIZAR_COR() na tabela VEICULO
CREATE OR REPLACE TRIGGER TRG_NORMALIZAR_COR
BEFORE INSERT OR UPDATE ON VEICULO
FOR EACH ROW
EXECUTE FUNCTION NORMALIZAR_COR();


-- Trigger que executa a função CONTROLAR_ESTOQUE() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER TRG_ESTOQUE_INSERT_UPDATE_DELETE
AFTER INSERT OR UPDATE OR DELETE ON ITEM_ORDEM
FOR EACH ROW
EXECUTE FUNCTION CONTROLAR_ESTOQUE();


-- Trigger que executa a função CALCULAR_VALOR_DE_ORDEM_DE_SERVICO() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER TRG_CALCULAR_VALOR_DE_ORDEM_DE_SERVICO
AFTER INSERT OR UPDATE OR DELETE ON ITEM_ORDEM
FOR EACH ROW
EXECUTE FUNCTION CALCULAR_VALOR_DE_ORDEM_DE_SERVICO();


-- Trigger que executa a função APLICAR_DESCONTO_ANIVERSARIO na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_APLICAR_DESCONTO_ANIVERSARIO
AFTER INSERT ON ORDEM_SERVICO
FOR EACH ROW
EXECUTE FUNCTION APLICAR_DESCONTO_ANIVERSARIO();


-- Trigger que executa a função IMPEDIR_DELETE_DE_CLIENTE_OS() na tabela CLIENTE
CREATE OR REPLACE TRIGGER TRG_IMPEDIR_DELETE_DE_CLIENTE_COM_OS
BEFORE DELETE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION IMPEDIR_DELETE_DE_CLIENTE_COM_OS();


-- Trigger que executa a função IMPEDIR_DELETE_DE_ITEM_UTILIZADO() na tabela ITEM
CREATE OR REPLACE TRIGGER TRG_IMPEDIR_DELETE_DE_ITEM_UTILIZADO
BEFORE DELETE ON ITEM
FOR EACH ROW
EXECUTE FUNCTION IMPEDIR_DELETE_DE_ITEM_UTILIZADO();


-- Trigger que executa a função DEFINIR_DATA_DE_EMISSAO_PADRAO() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_DEFINIR_DATA_DE_EMISSAO_PADRAO
BEFORE INSERT ON ORDEM_SERVICO
FOR EACH ROW
EXECUTE FUNCTION DEFINIR_DATA_DE_EMISSAO_PADRAO();


-- Trigger que executa a função PARABENIZAR_CLIENTE_ANIVERSARIANTE() na tabela CLIENTE
CREATE OR REPLACE TRIGGER TRG_PARABENIZAR_CLIENTE_ANIVERSARIANTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION PARABENIZAR_CLIENTE_ANIVERSARIANTE();


-- Trigger que executa a função atualizar_valor_ordem() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER trg_calcular_valor_de_ordem_de_servico
AFTER INSERT OR UPDATE OR DELETE ON item_ordem
FOR EACH ROW
EXECUTE FUNCTION atualizar_valor_ordem();


-- Trigger que executa a função REGISTRAR_LOG() na tabela CLIENTE
CREATE OR REPLACE TRIGGER TRG_LOG_CLIENTE
AFTER INSERT OR UPDATE OR DELETE ON CLIENTE
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela FUNCIONARIO
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIO
AFTER INSERT OR UPDATE OR DELETE ON FUNCIONARIO
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela ITEM
CREATE OR REPLACE TRIGGER TRG_LOG_ITEM
AFTER INSERT OR UPDATE OR DELETE ON ITEM
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER TRG_LOG_ITEM_ORDEM
AFTER INSERT OR UPDATE OR DELETE ON ITEM_ORDEM
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela MODELO
CREATE OR REPLACE TRIGGER TRG_LOG_MODELO
AFTER INSERT OR UPDATE OR DELETE ON MODELO
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela MONTADORA
CREATE OR REPLACE TRIGGER TRG_LOG_MONTADORA
AFTER INSERT OR UPDATE OR DELETE ON MONTADORA
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_LOG_ORDEM_SERVICO
AFTER INSERT OR UPDATE OR DELETE ON ORDEM_SERVICO
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela TIPO_ITEM
CREATE OR REPLACE TRIGGER TRG_LOG_TIPO_ITEM
AFTER INSERT OR UPDATE OR DELETE ON TIPO_ITEM
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função REGISTRAR_LOG() na tabela VEICULO
CREATE OR REPLACE TRIGGER TRG_LOG_VEICULO
AFTER INSERT OR UPDATE OR DELETE ON VEICULO
FOR EACH ROW 
EXECUTE FUNCTION REGISTRAR_LOG();


-- Trigger que executa a função IMPEDIR_QUANTIDADE_NEGATIVA_DE_ITEM() na tabela ITEM
CREATE OR REPLACE TRIGGER TRG_IMPEDIR_QUANTIDADE_NEGATIVA_DE_ITEM
BEFORE INSERT OR UPDATE ON ITEM
FOR EACH ROW
EXECUTE FUNCTION IMPEDIR_QUANTIDADE_NEGATIVA_DE_ITEM();


-- Trigger que executa a função VALIDAR_QUANTIDADE_DE_ITEM_ORDEM() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER TRG_VALIDAR_QUANTIDADE_DE_ITEM_ORDEM
BEFORE INSERT OR UPDATE ON ITEM_ORDEM
FOR EACH ROW
EXECUTE FUNCTION VALIDAR_QUANTIDADE_DE_ITEM_ORDEM();


-- Trigger que executa a função IMPEDIR_ITEM_DUPLICADO() na tabela ITEM_ORDEM
CREATE OR REPLACE TRIGGER trg_impedir_item_duplicado
BEFORE INSERT ON item_ordem
FOR EACH ROW
EXECUTE FUNCTION impedir_item_duplicado();


-- Trigger que executa a função VALIDAR_COD_STATUS() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_VALIDAR_COD_STATUS
BEFORE INSERT OR UPDATE ON ORDEM_SERVICO
FOR EACH ROW
EXECUTE FUNCTION VALIDAR_COD_STATUS();


-- Trigger que executa a função VALIDAR_DESCONTO() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_VALIDAR_DESCONTO
BEFORE INSERT OR UPDATE ON ORDEM_SERVICO
FOR EACH ROW
EXECUTE FUNCTION VALIDAR_DESCONTO();


-- Trigger que executa a função VALIDAR_VALOR_DE_OS() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER trg_validar_valor_de_os
BEFORE INSERT OR UPDATE ON ordem_servico
FOR EACH ROW
EXECUTE FUNCTION validar_valor_de_os();


-- Trigger que executa a função PROTEGER_DATA_EMISSAO() na tabela ORDEM_SERVICO
CREATE OR REPLACE TRIGGER TRG_PROTEGER_DATA_EMISSAO
BEFORE INSERT OR UPDATE ON ORDEM_SERVICO
FOR EACH ROW
EXECUTE FUNCTION PROTEGER_DATA_EMISSAO();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela CLIENTE
CREATE TRIGGER trg_impedir_pk_cliente
BEFORE INSERT ON cliente
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela FUNCIONARIO
CREATE TRIGGER trg_impedir_pk_funcionario
BEFORE INSERT ON funcionario
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela VEICULO
CREATE TRIGGER trg_impedir_pk_veiculo
BEFORE INSERT ON veiculo
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela MODELO
CREATE TRIGGER trg_impedir_pk_modelo
BEFORE INSERT ON modelo
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela MONTADORA
CREATE TRIGGER trg_impedir_pk_montadora
BEFORE INSERT ON montadora
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela ITEM
CREATE TRIGGER trg_impedir_pk_item
BEFORE INSERT ON item
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela TIPO_ITEM
CREATE TRIGGER trg_impedir_pk_tipo_item
BEFORE INSERT ON tipo_item
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela ORDEM_SERVICO
CREATE TRIGGER trg_impedir_pk_ordem_servico
BEFORE INSERT ON ordem_servico
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();


-- Trigger que executa a função IMPEDIR_PK_DUPLICADA() na tabela ITEM_ORDEM
CREATE TRIGGER trg_impedir_pk_item_ordem
BEFORE INSERT ON item_ordem
FOR EACH ROW
EXECUTE FUNCTION impedir_pk_duplicada();

